include:
  - local: '.gitlab/includes/common_pipeline.yml'

stages:
  - build
  - test

variables:
  UENV_IMAGE: "prgenv-gnu/25.07-6.3.3:v5"
  WITH_UENV_VIEW: "default-llvm-amdgpu"


build_parallel_algos_mi300:
  extends:
    - .uenv-runner-beverin-mi300
    - .cmake_common
    - .build_common
  stage: build
  image: $UENV_IMAGE
  script:
    - cmake --version
    - hipcc --version || echo "HIP not found in PATH"

    - cmake -B build_parallel_algos $CMAKE_COMMON_FLAGS -S parallel_algos -DWITH_HIP=ON
        -DWITH_CUDA=OFF
    - cmake --build build_parallel_algos

  artifacts:
    paths:
      - build_parallel_algos/
    expire_in: 1 hour


test_parallel_algos_mi300:
  needs: [build_parallel_algos_mi300]
  extends:
    - .uenv-runner-beverin-mi300
    - .test_common
  stage: test
  image: $UENV_IMAGE
  script:
    - ctest --test-dir build_parallel_algos --output-on-failure
